### ISSUE TITLE
Cannot find module 'socket.io-client' or its corresponding type declarations

### ISSUE THREAD

**Issue by Anmar03** [laravel/echo#528]
### Echo Version

2.3.7

### Laravel Version

12.0

### PHP Version

8.4

### NPM Version

10.9.8

### Description

After upgrading from v2.3.4 to v2.3.7, TypeScript builds now fail when skipLibCheck is disabled.

Our application uses Laravel Reverb with the Pusher transport and does not use Socket.IO. However, the type declarations shipped with Echo now appear to contain direct imports of socket.io-client:

import { io } from 'socket.io-client';
import { Socket } from 'socket.io-client';

These imports are in dist/echo.d.ts, causing TypeScript to attempt module resolution for socket.io-client during static analysis.

This causes the build fail with:

node_modules/laravel-echo/dist/echo.d.ts:3:20 - error TS2307: Cannot find module 'socket.io-client' or its corresponding type declarations.

3 import { io } from 'socket.io-client';
                     ~~~~~~~~~~~~~~~~~~

node_modules/laravel-echo/dist/echo.d.ts:5:24 - error TS2307: Cannot find module 'socket.io-client' or its corresponding type declarations.

5 import { Socket } from 'socket.io-client';

### Steps To Reproduce

1. Create a new laravel repo with a react frontend
3. Run `php artisan install:broadcasting --reverb`
4. Set SkipLibCheck to false.
5. Run `npx tsc --noEmit`
